version: "3"

services:
  api:
    build: .
    depends_on:
      - postgres
    #network_mode: "host"
    ports:
      - 10000:10000
        #env_file:
        #  - ./.env
    #volumes:
     # - ./:/usr/src/app:ro
    #command: uvicorn app.main:app --host 0.0.0.0 --port 10000 

    environment:
      - DATABASE_DRIVER=asyncpg
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password123
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_HOST=postgres
      - SECRET_KEY=70a470ad09c28148da5250061c34433e
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes: 
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

     

      

